import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.css'
import './global.css'
import type { AppProps } from 'next/app'


export const metadata = {
  title: 'Derek P',
  description: 'Generated by create next app',
};

function MyApp({ Component, pageProps }:AppProps) {
  return (
    <>
      <Head>
        <title>Derek P</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;